### DISCUSSION TITLE
New automatitation, scheduller

### DISCUSSION THREAD

**Discussion by Imanol82** [Imanol82/Baxi-Dietrich-Remeha-to-Home-Assistant-with-an-ESP32#5] [Announcements]
Hello.

I have been using the project for months and it works very well. I am very happy.

Now I have made an automation to activate different schedulers. 
I'm posting it in case anyone is interested.

We have the following programs:
- Office (when we are working outside home)
- Teleworking (when we are teleworking)
- Holiday (when it is a holiday)
- Saturday
- Sunday

![image](https://github.com/user-attachments/assets/2115a36c-9925-4c94-acdb-4ab298ef0291)

It is very easy to use.
If the Scheduler button is ON, you can select Saturday, Sunday and one of the other 3 buttons (Office, Telework and Holiday)
When you turn off the Scheduler button, all scheduler are deactivated.

You can only select one of the 3 buttons, Office, Telework and Holiday at a time.
Saturday and Sunday are separate.

Then, each scheduler is more or less like this:

![image](https://github.com/user-attachments/assets/c6dd4ee6-1b30-406a-9bff-3b8bd887c196)

The next step will be to make the teleworking process automatic. Home Assistant will detect when a mobile is at home during the week at 9:00 to activate the Teleworking program.

Short video:

[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/QCT18ky1hMM/0.jpg)](https://www.youtube.com/watch?v=QCT18ky1hMM)

```
- alias: Control de Programas de CC
  id: '1741435234653'
  description: ''
  triggers:
  - entity_id: input_boolean.programa
    trigger: state
  - entity_id:
    - switch.schedule_oficina
    - switch.schedule_teletrabajo
    - switch.schedule_festivo
    trigger: state
  - entity_id:
    - switch.schedule_sabado
    - switch.schedule_domingo
    trigger: state
  conditions: []
  actions:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.programa
        state: 'off'
      sequence:
      - target:
          entity_id:
          - switch.schedule_oficina
          - switch.schedule_teletrabajo
          - switch.schedule_festivo
          - switch.schedule_sabado
          - switch.schedule_domingo
        action: switch.turn_off
        data: {}
  - choose:
    - conditions:
      - condition: state
        entity_id: switch.schedule_oficina
        state: 'on'
      - condition: template
        value_template: '{{ trigger.entity_id == ''switch.schedule_oficina'' }}'
      sequence:
      - target:
          entity_id:
          - switch.schedule_teletrabajo
          - switch.schedule_festivo
        action: switch.turn_off
        data: {}
    - conditions:
      - condition: state
        entity_id: switch.schedule_teletrabajo
        state: 'on'
      - condition: template
        value_template: '{{ trigger.entity_id == ''switch.schedule_teletrabajo'' }}'
      sequence:
      - target:
          entity_id:
          - switch.schedule_oficina
          - switch.schedule_festivo
        action: switch.turn_off
        data: {}
    - conditions:
      - condition: state
        entity_id: switch.schedule_festivo
        state: 'on'
      - condition: template
        value_template: '{{ trigger.entity_id == ''switch.schedule_festivo'' }}'
      sequence:
      - target:
          entity_id:
          - switch.schedule_oficina
          - switch.schedule_teletrabajo
        action: switch.turn_off
        data: {}
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.entity_id in [''switch.schedule_oficina'', ''switch.schedule_teletrabajo'',
          ''switch.schedule_festivo''] and is_state(trigger.entity_id, ''off'') }}'
      sequence:
      - stop: Se ha deseleccionado una opción, no se activará ninguna otra.
  - choose:
    - conditions:
      - condition: state
        entity_id: input_boolean.programa
        state: 'off'
      - condition: or
        conditions:
        - condition: state
          entity_id: switch.schedule_sabado
          state: 'on'
        - condition: state
          entity_id: switch.schedule_domingo
          state: 'on'
      sequence:
      - target:
          entity_id:
          - switch.schedule_sabado
          - switch.schedule_domingo
        action: switch.turn_off
        data: {}
  mode: restart
```

Thanks!
